import turtle as t 
t.speed(-100)
t.pensize(6)
t.penup()
t.goto(-480,700)
t.write("CHESS BOARD", font=("Arial", 26 , "normal"))
t.pendown()
t.bgcolor('#966F33')
t.penup()
t.goto(0,-500)
t.fd(500)
t.lt(90)
t.pendown()
for i in range(4):
      t.fd(1000)
      t.lt(90)
      
t.penup()
t.fd(500)
t.lt(90)
t.pendown()
t.fd(1000)
      
t.penup ()
t.rt(90)
t.fd(500)
t.rt(90)
t.pendown()

t.penup()
t.fd(500)
t.rt(90)
t.pendown()
t.fd(1000)
t.goto(0,-250)
t.penup()
t.goto(500,0)
t.rt(90)
t.pendown()
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.penup()
t.goto(500,-125)
t.pendown()
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.penup()
t.goto(500,-250)
t.pendown()
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.penup()
t.goto(500,-375)
t.pendown()
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.penup()
t.goto(500,500)
t.pendown()
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.penup()
t.goto(500,375)
t.pendown()
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.penup()
t.goto(500,250)
t.pendown()
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.penup()
t.goto(500,125)
t.pendown()
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('black')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.fd(125)
t.fillcolor('white')
t.begin_fill()
for i in range(4):
            t.fd(125)
            t.lt(90)
t.end_fill()
t.penup()
t.goto(-250,-750)
t.pendown()
t.write("Developed by SSKC236")
t.hideturtle()
t.done()